name: 问题反馈-零号空洞-枯萎之都
description: 枯萎之都有问题的时候提这个
title: "[问题反馈] [枯萎之都] "
labels: ["Triage | 待检查"]

body:
  - type: markdown
    attributes:
      value: |
        ## 前置须知

        - 请先将代码更新至最新版本尝试是否依然有问题。
        - 最新版本代码有问题可尝试使用回滚功能看是否依然有问题。
        - __请先在 issue 中搜索是否已有类似问题 请先在 issue 中搜索是否已有类似问题 请先在 issue 中搜索是否已有类似问题__。
        - 请先阅读最新的[使用前须知](https://one-dragon.org/zzz/zh/quickstart.html#_2-%E4%BD%BF%E7%94%A8%E5%89%8D%E9%A1%BB%E7%9F%A5)，确保设置正确。
        - 请先阅读最新的[功能说明](https://one-dragon.org/zzz/zh/docs/feat_hollow_zero.html)，确保设置正确。
        - 请使用 __脚本F11__ 进行截图上传，其他截图方式大概率不受理。
        - 请使用 __脚本F11__ 进行截图上传，其他截图方式大概率不受理。
        - 请使用 __脚本F11__ 进行截图上传，其他截图方式大概率不受理。
        - 缺少日志/截图/录屏的情况，有概率不受理。

  - type: checkboxes
    id: check
    attributes:
      label: 请确认您已完成以下几件事
      description: 游戏版本更新后，新版本内容需要一定时间(至少一周)适配，请耐心等待
      options:
        - label: 正在使用最新的 OneDragon
        - label: 已搜索过 issue 中无人提出相似问题或无解决方案
        - label: 已为所有模型以及战斗脚本更新至最新版
          required: true
        - label: 运行时无任何帧率显示或其他覆盖层窗口遮盖游戏
          required: true
        - label: 未安装任何修改游戏UI和贴图的模组
          required: true

  - type: input
    attributes:
      label: 代码版本
      description: "窗口上方显示 点击可复制到粘贴板 不填入大概率不受理"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 问题反馈

  - type: textarea
    attributes:
      label: "问题描述"
      description: "请理解每个人的运行环境都不一样，为了知道如何修复问题，需要你详细描述重现这个问题的步骤，请当作者是没玩过游戏的人来讲解问题，如果作者无法重现，则大概率不受理。"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "问题副本"
      description: "是在哪个副本里触发这个问题的，方便作者复现"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "寻路方式"
      description: "如果是在格子移动上卡死，提供速通还是默认还是自定义，方便作者复现"

  - type: textarea
    attributes:
      label: "游戏截图"
      description: |
        - 请使用 __脚本F11__ 进行截图上传，图片保存在 .debug/images/ 文件夹中，其他截图方式大概率不受理。
        - 请使用 __脚本F11__ 进行截图上传，图片保存在 .debug/images/ 文件夹中，其他截图方式大概率不受理。
        - 请使用 __脚本F11__ 进行截图上传，图片保存在 .debug/images/ 文件夹中，其他截图方式大概率不受理。
      placeholder: "游戏截图"

  - type: textarea
    attributes:
      label: "运行日志"
      description: "日志保存在 .log/log.txt 中"
      placeholder: "运行日志"

  - type: textarea
    attributes:
      label: "你的建议"
      description: "针对这个场景，你觉得合适的解决方案是"
      placeholder: "你的建议"
